sudo: required
language: cpp
services:
- docker
env:
  global:
    secure: X7BkOUOR2nt35IxLFFmpTPAVcgQ/SuSbuanXAheDj1tY4F+7MgEl/kDa+QV0mNG3EIvRhkY4+pmcBjgux8SF4MfPiFPD7XG7V0LPbHRWEWfzLIzJkVeErA8IAqwI0/IWQXEOOmQ9ElRygaKX1Tdot1piV99DSw+eGhtLnGIedKo=
before_install:
- docker pull ubuntu:16.04
- docker pull ubuntu:14.04
script:
- docker build --tag qhttpserver-ubuntu16 --build-arg BINTRAYKEY=$BINTRAYKEY  --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER
  -f ./Dockerfile-ubuntu16.04 .
- docker build --tag qhttpserver-ubuntu14 --build-arg BINTRAYKEY=$BINTRAYKEY  --build-arg TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER
  -f ./Dockerfile-ubuntu14.04 .
after_success:
- docker run -t -d qhttpserver-ubuntu16
- docker cp $(docker ps -n 1 -q):/src/qhttpserver/build/qhttpserver-0.0.1-Linux.deb
  $HOME/qhttpserver-0.0.1-ubuntu16.deb
- docker run -t -d qhttpserver-ubuntu14
- docker cp $(docker ps -n 1 -q):/src/qhttpserver/build/qhttpserver-0.0.1-Linux.deb
  $HOME/qhttpserver-0.0.1-ubuntu14.deb
before_deploy:
- git config --local user.name "Gael de Chalendar"
- git config --local user.email "kleag@free.fr"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: F16J7J9a+VNEBwSiAksWxnF7c1M8Zg0+Tg8WGRRYy2p5aqR83Gj8/3M+SIPNw/Dzxj8+Sid1QkIZ42jISzoDKO3bJ0cX7ymqGy3bwqMMsue6l2TAa/heJKpaGroyLtjZRgD2pGtHigC8W1BOEz+5KhVBwWAYDF92TpluvyklGoA=
  file_glob: true
  file: $HOME/*.deb
  skip_cleanup: true
  on:
    repo: aymara/qhttpserver
    tags: false
    all_branches: true
