language: cpp
compiler: gcc
env: 
  global:
    - secure: FlsmywHiGR6VKejCGcEd59rhvk5YI1f+FUAWfBLVxzqG4haLGT0MQwyxDr2EPS3Iu+v16nsMxHT2dwMCotC8zTPSmHUr6evE4jpNcqs+vIOAz7VLjdqwD0jweeguOR4JxL1XcgFZMAPTnoQFBFZlEOFu8OxaDjOoG7Oj0iGH+Fo=
install:
- cat /etc/*-release
- echo `echo 2 | sudo update-alternatives --config gcc`
- sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
- sudo apt-get update
- sudo apt-get install -qq -y cmake gdb
- sudo add-apt-repository --yes ppa:beineri/opt-qt532
- sudo apt-get update -qq
- sudo apt-get install -qq -y qt53base  qt53tools
script: pwd && mkdir dist && mkdir build && cd build && cmake .. && make && make package
after_success:
- curl -T /home/travis/build/aymara/qhttpserver/build/qhttpserver-0.0.1-Linux.deb -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-12.04/qhttpserver/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/qhttpserver-0.0.1-Linux.deb
- curl -XPOST -ukleag:$BINTRAYKEY https://api.bintray.com/content/kleag/ubuntu-12.04/qhttpserver/$TRAVIS_JOB_NUMBER/publish
- curl -XGET https://bintray.com/kleag/ubuntu-12.04/qhttpserver/$TRAVIS_JOB_NUMBER
