#init:
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
branches:
  except:
    - /^\d\d\d\d\d\d\d\d\d\d\d\d\d\d-[\da-f]+$/


environment:
  QTDIR: 'C:\Qt\5.11.0\msvc2015_64'
  PATH: '%QTDIR%\bin;c:\d\bin;%PATH%'
  GITHUB_OAUTH_TOKEN:
    secure: 01sh5OxKgkUJbTt/ldX/duLQk6iP28Iwet3reW8FK8f7Z3xiM2RLHQUwOzZye4qs

configuration: Release

os: Visual Studio 2015

install:
  ############################################################################
  # All external dependencies are installed in C:\externals
  ############################################################################
  - mkdir C:\externals
  - cd C:\externals

  ############################################################################
  # Install Ninja
  ############################################################################
  - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
  - 7z x ninja.zip -oC:\externals\ninja > nul
  - set PATH=C:\externals\ninja;%PATH%
  - ninja --version


build_script:
  - ps: pushd c:/projects/qhttpserver
  - ps: $env:VERSION_RELEASE="$(git log --date=iso  -1 | grep Date | sed -e 's/Date:\ *//' -e 's/\+.*//' -e 's/[- :]//g')-$(git log --format=%h --abbrev=8 -1)"
  - echo %VERSION_RELEASE%
  - ps: popd
  - mkdir c:\b
  - cd c:\b

  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cmake -G "Ninja" "-DCMAKE_PREFIX_PATH=%QTDIR%" "-DCMAKE_IGNORE_PATH=C:/msys64/usr/bin" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=c:\d" "-DVERSION_RELEASE:STRING=%VERSION_RELEASE%" c:/projects/qhttpserver
  - cmake --build . --config Release
  - cmake --build . --target package --config Release


after_build:
  - ps: pushd C:\b
  - copy qhttpserver*.exe %APPVEYOR_BUILD_FOLDER%
  - ps: popd


artifacts: 
  - path: qhttpserver*.exe
    name: packages

deploy:
  description: '$(VERSION_RELEASE)'
  provider: GitHub
  tag: $(VERSION_RELEASE)
  auth_token:
    secure: 01sh5OxKgkUJbTt/ldX/duLQk6iP28Iwet3reW8FK8f7Z3xiM2RLHQUwOzZye4qs
  artifact: packages
  force_update: true


on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

